# server:
#   port:

# spring:
#   mvc:
#     view:
#       prefix:
#       suffix:
#   datasource:
#     url:
#     username:
#     password:
#     driver-class-name:
#   rabbitmq:
#     host:
#     port:
#     username: 
#     password:
#     ssl:
#       enabled:
#     queue:
#       name:
#     exchange:
#       name: 
#     routing:
#       key: 

# mybatis:
#   type-aliases-package:
#   mapper-locations:

# kakao:
#   api:
#     key: 